### ISSUE TITLE
Categories in examples not consistent.

### ISSUE THREAD

**Issue by AudTheCodeWitch** [learn-co-curriculum/programming-univbasics-4-nested-hashes-readme#2]
In the text, you refer to the categories as "instructors, students, classes." However, this naming structure is inconsistent with the keys provided in your code sample. Instead, you have instructors: dev_team: and classes:. Please update dev_team: to students: for consistency in your example.

**Comment by sgharms** [comment]
Great eye! Changed, thanks.
